### ISSUE TITLE
Cannot apply custom styling? (Kongregate/Standalone, Chrome)

### ISSUE THREAD

**Issue by airpants** [erosson/swarm-graphics#1]
- :honeybee: _First of all_, I am really excited that you're letting us play with the styling if we want. That's super cool of you. I'm still early in the game, but I hope you keep updating it!
- :honeybee: _Second of all_, I have never used GitHub until this point, so please excuse my incredible ignorance. 
- :honeybee: I'm completely stymied as to **how to get the import function to work in the custom styling box**. It works for `kittens.css` and `graphics.css` if they are linked from what appears to be the swarmsim root, but not if they are linked directly using `@import url('http://erosson.github.io/swarm-graphics/graphics.css');`
  - In addition, I can't seem to import a .css file hosted in my own GH repository. Am I missing something? I followed your directions in the README and they make sense in theory, but not in practice.

:honeybee: Cheers!:honeybee:

**Comment by airpants** [comment]
Never mind, I am literally an idiot. Buzz. Imported CSS must be called with `https://`, not `http://`.
Imma sprite some mean lookin' bugs now.
![Droooooooooone](http://piskel-imgstore-b.appspot.com/img/9463d3f8-f3a7-11e4-9833-39996fd08e19.gif)

**Comment by erosson** [comment]
Hey, glad to hear you got this working. I've made the same http/https mistake before, it's an easy thing to miss. In fact, I think I'll make this clearer in the readme, thanks for pointing it out!

Nice start, btw, I'd love to see whatever graphics you come up with.

> I hope you keep updating it!

That's the plan :)

**Comment by airpants** [comment]
Thanks! Glad my fumble can be of use.

I'll be poking CSS with a stick and puking pixels at [airpants/swarmsim-styling](https://github.com/airpants/swarmsim-styling). It's likely to take a literal age to complete, but so far I'm having fun. 8D
